### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by sdauwh** [BasuCert/WinboxPoC#34]
@Deantwo I'm a fresh, when I exec WinboxExploit.py it shows as below:
d:\123>python WinboxExploit.py 192.168.120.9
  File "WinboxExploit.py", line 7
    !DOCTYPE html
    ^
SyntaxError: invalid syntax

I'm trying many times to type python3 WinboxExploit.py 192.168.120.9 but it shows the "python3" is not internal or external order.
My python version is 3.7

Thanks for your help!

**Comment by Deantwo** [comment]
The [WinboxExploit.py](https://github.com/BasuCert/WinboxPoC/blob/master/WinboxExploit.py) doesn't contain the text `!DOCTYPE html`, so it looks like you might not have copied the script correctly.

**Comment by sdauwh** [comment]
@Deantwo Yes, my fault, I save as the WinboxExploit.py as attachment directly which doesn't contain the script. Now I just test and it works but return back:
### d:\123>python WinboxExploit.py 192.168.120.9
Connected to 192.168.120.9:8291
Exploit failed

I review the comments you have given long time ago that find maybe the RouterOS version problem, so how can I check the RouterOS version. I'm in the company LAN and each user has it's own account and password. 

Thanks!

**Comment by Deantwo** [comment]
Yeah `Exploit failed` just means that the exploit didn't get any information it could use. So it is likely because the RouterOS version you are using isn't vulnerable to the exploit. You can see a details on what versions are vulnerable in the [README.dm](https://github.com/BasuCert/WinboxPoC/blob/master/README.md).

**Comment by sdauwh** [comment]
Yes, I scanned the server found it is RouterOS 5.25. So if RouterOS 5.25 has any vulnerable?

Thanks!

**Comment by Chupaka** [comment]
You cannot use this exploit on version 5.25, only on v6.29-6.42

**Comment by Deantwo** [comment]
RouterOS v5.25 is a really really old version. It was released in 2013-04-29.
See: https://mikrotik.com/download/changelogs
I don't know anything about that RouterOS version, since it was before my time.

If you are looking for help with saving your configuration from that router, I suggest writing on the MikroTik forum and ask for help.

**Comment by mosajjal** [comment]
I think the docs are pretty clear about the vulnerable version :) Closing this
